parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "simple-import-sort"
  - "security-node"
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:security-node/recommended
env:
  node: true
  jest: true
rules:
  "@typescript-eslint/adjacent-overload-signatures": 2
  "@typescript-eslint/no-var-requires": 2
  "@typescript-eslint/no-unused-vars": 2
  "@typescript-eslint/no-explicit-any": 0
  eqeqeq: 2
  no-console: 2
  no-debugger: 2
  no-duplicate-imports: 2
  no-else-return: 2
  no-empty-function:
    - 2
    - allow:
      - constructors
  no-extra-boolean-cast: 2
  no-multi-spaces: 2
  no-unreachable: 2
  prefer-template: 1
  require-await: 2

